paths:
  textures: models/textures
  map_textures: models/map_textures
  models: models
  model_sizes: models/sizes.yaml
  maps: maps

map_texture_size: 256

camera:
  min_distance: 3
  max_distance: 30
  init_distance: 10
  init_vertical_angle: -90
  horizontal_angle: 60

player:
  model: ninja
  pointer_texture: pointer
  walk_range: [0, 12]
  pre_jump_range: [103, 106]
  jump_range: [107, 110]
  idle_frame: 28
  speed: 2
  init_position: [11, 4]