paths:
  textures: models/textures
  map_textures: models/map_textures
  models: models
  model_sizes: models/sizes.yaml
  maps: maps

map_texture_size: 256

camera:
  min_distance: 3
  max_distance: 30
  distance_step: 1
  init_distance: 30
  init_vertical_angle: -90
  vertical_angle_step: 3
  horizontal_angle: 60

character:
  walk_range: [0, 12]
  death_speed: 1
  death_range: [165, 170]

player:
  model: ninja
  texture: nskinbl
  speed: 2
  pointer_texture: pointer
  pre_jump_range: [103, 106]
  pre_jump_speed: 0.7
  post_jump_range: [107, 110]
  post_jump_speed: 0.7
  jump_height: 0.5
  init_position: [11, 4]
  idle_frame: 28

npc:
  init_position: [11, 4]
  speed: 2
  idle_frame: 28