paths:
  textures: models/textures
  map_textures: models/map_textures
  models: models
  model_sizes: models/sizes.yaml
  maps: maps

map_texture_size: 256

camera:
  min_distance: 3
  max_distance: 30
  distance_step: 1
  init_distance: 30
  init_vertical_angle: -90
  vertical_angle_step: 3
  horizontal_angle: 60

character:
  animation:
    walk_range: [0, 12]
    death_speed: 1
    death_range: [165, 170]

player:
  model: ninja
  texture: nskinbl
  speed: 2
  pointer_texture: pointer
  jump_height: 0.5
  animation:
    pre_jump_range: [103, 106]
    pre_jump_speed: 0.7
    post_jump_range: [107, 110]
    post_jump_speed: 0.7
    hit_range: [44, 48]
    hit_speed: 1
    post_hit_range: [49, 58]
    post_hit_speed: 0.7
  init_position: [11, 4]
  idle_frame: 28

npc:
  speed: 1.8
  normal_view_radius: 7
  normal_view_angle: 80
  animation:
    hit_range: [59, 63]
    hit_speed: 0.7
    post_hit_range: [64, 67]
    post_hit_speed: 0.7
  idle_frame: 28