paths:
  textures: graphic_objects/textures
  map_textures: graphic_objects/map_textures
  map_backgrounds: graphic_objects/map_backgrounds
  models: graphic_objects/models
  model_sizes: graphic_objects/sizes.yaml
  maps: maps
  map_thumbnails: graphic_objects/map_thumbnails

# for debugging
show_view_field: false 
show_pathes: false
invisible_player: false 
respawn_player: false 
   
text_scale: 0.03
menu_background: graphic_objects/menu_background.jpg
preloader_image: graphic_objects/preloader.jpg
fail_background: graphic_objects/fail_background.jpg
win_background: graphic_objects/win_background.jpg

graphics:
  background_stretch_factor: 1.8
  map_texture_size: 256
  transparency: 0.3 # for showing player inside models
  shadow_size: 512
  light_color: [1, 1, 1]
  ambient_light_color: [0.4, 0.4, 0.4]
  enable_shadows: false 
  enable_cartoon: true

camera:
  min_distance: 3
  max_distance: 30
  distance_step: 1
  init_distance: 30
  init_vertical_angle: -45
  vertical_angle_step: 3
  horizontal_angle: 60 # if less than 69 then appear issues with transparent objects

character:
  resume_action_timeout: 0.1
  animation:
    walk_range: [0, 12]
    death_speed: 0.3
    backward_death_range: [165, 170]
    forward_death_range: [175, 182]
    pick_up_speed: 0.5
    pick_up_range: [82, 92]

player:
  texture: nskinbl
  speed: 2
  pointer_texture: blue_pointer
  jump_height: 0.5
  animation:
    pre_jump_range: [103, 106]
    pre_jump_speed: 0.7
    post_jump_range: [107, 110]
    post_jump_speed: 0.7
    hit_range: [44, 48]
    hit_speed: 1
    post_hit_range: [49, 58]
    post_hit_speed: 0.7
    body_moving_range: [14, 29]
  idle_frame: 28
  body_captured_frame: 14
  body_moving_speed: 3 #1

npc:
  alert_radius: 5
  speed: 1.5
  excited_speed: 2.3
  normal_view_radius: 7
  normal_view_angle: 80
  excited_view_radius: 10
  excited_view_angle: 120
  animation:
    hit_range: [59, 63]
    hit_speed: 0.7
    post_hit_range: [64, 67]
    post_hit_speed: 0.7
  idle_frame: 28
  body_frame: 170
  body_shift: -2

target_npc:
  escape_speed: 2.5

show_control_keys: true 

control_keys:
- close_window: escape
- rotate_camera_clockwise: x
- rotate_camera_counterclockwise: z
- increase_camera_distance: a
- decrease_camera_distance: s
- move_forward: arrow_up
- move_backward: arrow_down
- move_left: arrow_left
- move_right: arrow_right
- jump: space
- kill_self: k
- hit: h
- move_body: b
