paths:
  textures: models/textures
  map_textures: models/map_textures
  models: models
  model_sizes: models/sizes.yaml
  maps: maps

show_view_field: false # for debugging
show_pathes: true # for debugging

graphics:
  map_texture_size: 256
  light_hpr: [-90, -40, 0]
  light_color: [1, 1, 1, 1]
  ambient_light_color: [0.4, 0.4, 0.4, 1]
  #TODO: move this to user's settings
  enable_shadows: true
  enable_cartoon: true

camera:
  min_distance: 3
  max_distance: 30
  distance_step: 1
  init_distance: 30
  init_vertical_angle: -90
  vertical_angle_step: 3
  horizontal_angle: 60

character:
  animation:
    walk_range: [0, 12]
    death_speed: 0.3
    backward_death_range: [165, 170]
    forward_death_range: [175, 182]

player:
  texture: nskinbl
  speed: 3 #2
  pointer_texture: blue_pointer
  jump_height: 0.5
  animation:
    pre_jump_range: [103, 106]
    pre_jump_speed: 0.7
    post_jump_range: [107, 110]
    post_jump_speed: 0.7
    hit_range: [44, 48]
    hit_speed: 1
    post_hit_range: [49, 58]
    post_hit_speed: 0.7
    body_moving_range: [14, 29]
    pick_up_speed: 0.5
    pick_up_range: [82, 92]
  idle_frame: 28
  body_captured_frame: 14
  body_moving_speed: 3 #1

npc:
  alert_radius: 5
  speed: 1.5
  excited_speed: 2.3
  normal_view_radius: 7
  normal_view_angle: 80
  excited_view_radius: 10
  excited_view_angle: 120
  animation:
    hit_range: [59, 63]
    hit_speed: 0.7
    post_hit_range: [64, 67]
    post_hit_speed: 0.7
  idle_frame: 28
  body_frame: 170
  body_shift: -2
