paths:
  textures: models/textures
  map_textures: models/map_textures
  models: models
  model_sizes: models/sizes.yaml
  maps: maps

map_texture_size: 256

camera:
  min_distance: 3
  max_distance: 30
  distance_step: 1
  init_distance: 10
  init_vertical_angle: -90
  vertical_angle_step: 3
  horizontal_angle: 60

player:
  model: ninja
  pointer_texture: pointer
  walk_range: [0, 12]
  pre_jump_range: [103, 106]
  pre_jump_speed: 0.7
  post_jump_range: [107, 110]
  post_jump_speed: 0.7
  death_range: [165, 170]
  death_speed: 0.1
  idle_frame: 28
  speed: 2
  jump_height: 0.5
  init_position: [11, 4]