border: 0.5 # x position of edit panel

camera:
  init_pos: [10, 2]
  init_height: 30
  init_vertical_angle: -90
  min_height: 3
  max_height: 30
  height_step: 1
  horizontal_move_step: 0.1
  vertical_angle_step: 3
  horizontal_angle: 60

pointer:
  move_camera_border: 0.1 # defines the region in which mouse cursor moves the camera

edit_panel:
  widget_scale: 0.05
  row_height: 0.06
  row_width: 7
  left_margin: 0.01
  row_poses:
    select_group: 0.1

show_control_keys: true
model_transparency: 0.3

control_keys:
- close_window: control-escape
- add_group: a
- save: s
- switch_transparency: t
- rotate_camera_clockwise: arrow_right
- rotate_camera_counterclockwise: arrow_left
- increase_camera_height: arrow_up
- decrease_camera_height: arrow_down
- set_group_for_square: mouse1
- select_group_by_square: lcontrol
- cancel_selection: escape